---

- name: "[IOS] Configure BGP neighbor"
  ios_config:
    parents:
      - router bgp {{ bgp.bgp_as }}
    lines:
      - bgp router-id {{ interfaces['Loopback1'].ip | ipaddr('address') }}
      - neighbor {{ item.peer_ip }} remote-as {{ item.peer_as }}
      - redistribute connected
  with_items: "{{ bgp.neighbors }}" 

